### PR TITLE
Evaluation script runs correctly e2e.

### LINKED ISSUE #19: `AttributeError: 'PandasIndex' object has no attribute 'coord_dtype'` during evaluation.py
The Dataflow pipeline fails here:

```
AttributeError: 'PandasIndex' object has no attribute 'coord_dtype' [while running 'evaluate_deterministic/DatasetToChunks|EvaluateChunk|TemporalMean/DatasetToChunks/KeyToChunks-ptransform-62']
```

I think it could be a dependencies issue, will look into this.

### PR DESCRIPTION
**Pull request by alxmrs**
By pinning the xarray version, I fixed #19, which was caused by mixed versions during serialization.

### CODE REVIEW

**Comment by raspstephan** [comment]
Can we also remove the pandas <=1.4 requirement to get rid of the colab error?

**Comment by alxmrs** [comment]
Yes we can. I believe that we have this max version requirement to ensure we're compatible with the internal version of pandas. One concern is that there could be pipeline differences between the two versions. 

Should we go for internal + external compatibility? or, revisit this only if we notice a problem (this is my preference)?

**Comment by raspstephan** [comment]
Let's just go for it and fix it if we encounter a problem

**Comment by alxmrs** [comment]
I remember why we pinned to that earlier version of pandas now. There was an API change in a commonly used function in 1.40, see: https://github.com/google-research/weatherbench2/actions/runs/5812376248/job/15757624675?pr=22

CC: @raspstephan.

**Comment by raspstephan** [comment]
Hmm, any way to prevent the colab conflict though?

**Comment by alxmrs** [comment]
I'll make a follow-up CL :)

**Pull request merged**
